version: "3.7"
services:
  kong:
    build:
      context: .
    environment:
      KONG_NGINX_CLIENT_BODY_BUFFER_SIZE: "32M"
      KONG_NGINX_CLIENT_MAX_BODY_SIZE: 0
      KONG_NGINX_CLIENT_HEADER_BUFFER_SIZE: "8k"
      KONG_NGINX_PROXY_BUFFER_SIZE: "32M"
      KONG_NGINX_PROXY_BUFFERS: "16 32M"
      KONG_NGINX_PROXY_LARGE_CLIENT_HEADER_BUFFERS: “16 8k”
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/share/kong.yml
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PLUGINS: bellatrix_bridge,cors,request-size-limiting,prometheus
      KONG_GO_PLUGINS_DIR: /usr/local/share/go-plugins
    ports:
      - "8000:8000/tcp"
      - "8444:8444/tcp"
  konga:
    image: pantsel/konga:next
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - "1337:1337"