version: "3.7"
services:
  kong:
    image: gcr.io/stord-nonprod/kong:${CIRCLE_WORKFLOW_ID}
    build:
      context: .
      args:
        REDIS_CACHE_URL: $REDIS_CACHE_URL
        SSL_CERTIFICATE_1: $NONPROD_SSL_CERTIFICATE_1
        SSL_CERTIFICATE_2: $NONPROD_SSL_CERTIFICATE_2
        SSL_CERTIFICATE_PRIVATE_KEY: $NONPROD_SSL_CERTIFICATE_PRIVATE_KEY
        SNI_NAME: $NONPROD_SNI_NAME
    ports:
      - "8000:8000/tcp"
      - "8444:8444/tcp"
  konga:
    image: pantsel/konga:next
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - "1337:1337"
