version: "3.7"
services:
  kong:
    image: stordco/kong
    build:
      context: .
      args:
        CLOUD_SIGNATURE_KEY: signature
        LD_SDK_KEY: replaceme
        KONG_LOG_LEVEL: debug
        SAIPH_URL: http://saiph:4001
        RIGEL_URL: http://rigel:4002
        USER_MANAGEMENT_URL: http://user-management:4003
        CLOUD_SERVICE_URL: http://host.docker.internal:4801
        MINTAKA_URL: http://mintaka:4004
        MEISSA_URL: http://meissa:4005
        ORDERS_SERVICE_URL: http://orders-service:4000
        FACILITY_ACTIVITY_SERVICE_URL: http://facility-activity-service:4000
        DOCUMENTS_SERVICE_URL: http://documents-service:4000
        INVENTORY_SERVICE_URL: http://inventory:4000
        TRADE_PARTNERSHIPS_SERVICE_URL: http://trade-partnerships-service:4000
        PRODUCT_CATALOG_SERVICE_URL: http://product-catalog-service:4000
        HEALTHCHECK_AGGREGATOR_SERVICE_URL: http://healthcheck-aggregator-service:4000
        MARKETPLACE_SERVICE_URL: http://marketplace-service:4000
        TENANT_SERVICE_URL: http://tenant-service:4000
        SEARCH_SERVICE_URL: http://search-service:4000
        WMS_INTEGRATION_BRIDGE_URL: http://wms-integration-bridge
        TRANSPORTATION_SERVICE_URL: http://transportation-service
        ORDER_ORCHESTRATION_SERVICE_URL: http://order-orchestration
        LOGIWA_READER_URL: http://logiwa-reader
        STORDBOT_URL: http://stordbot
        PLANNING_SERVICE_URL: http://planning-service:4000
    environment:
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000/tcp"
      - "8001:8001/tcp"
      - "8444:8444/tcp"
