version: "3.7"
services:
  kong-latest:
    build:
      target: ci
    image: gcr.io/stord-nonprod/kong:latest
  kong-tagged:
    build:
      target: ci
    image: gcr.io/stord-nonprod/kong:${CIRCLE_WORKFLOW_ID}
