version: "3.7"
services:
  kong:
    image: gcr.io/stord-nonprod/kong-local
    build:
      context: .
      args:
        KONG_TEMPLATE: kong.local.template.yml
        SAIPH_URL: http://saiph:4001
        RIGEL_URL: http://rigel:4002
        USER_MANAGEMENT_URL: http://user-management:4003
        MINTAKA_URL: http://mintaka:4004
        MEISSA_URL: http://meissa:4005
        ORDERS_SERVICE_URL: http://orders-service:4000
        FACILITY_ACTIVITY_SERVICE_URL: http://facility-activity-service:4000
        DOCUMENTS_SERVICE_URL: http://documents-service:4000
        ITEM_SERVICE_URL: http://item-service:4000
        INVENTORY_SERVICE_URL: http://inventory:4000
        TRADE_PARTNERSHIPS_SERVICE_URL: http://trade-partnerships-service:4000
        PRODUCT_CATALOG_SERVICE_URL: http://product-catalog-service:4000
    ports:
      - "8000:8000/tcp"
      - "8444:8444/tcp"
