image:
  repository: gcr.io/orion-sandbox/kong
  tag: ea9063dc-3a89-4ee7-994f-755b2d0f0850
  pullSecrets:
   - gcr-access-key

serviceMonitor:
  enabled: true

ingressController:
  enabled: false
  installCRDs: false

migrations:
  preUpgrade: false
  postUpgrade: false
runMigrations: false

postgresql:
  enabled: false

env:
  database: "off"
  plugins: bellatrix_bridge,cors,request-size-limiting,prometheus
  go_plugins_dir: /usr/local/share/go-plugins
  declarative_config: /usr/local/share/kong.yml

admin:
  enabled: true
  useTLS: false