version: 2.1

executors:
  builder:
    docker:
      - image: gcr.io/stord-nonprod/builder:latest
        auth:
          username: _json_key
          password: ${NONPROD_GCLOUD_SERVICE_KEY}

jobs:
  build-and-push:
    executor: builder
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Build Image  
          command: docker-compose build
      - run:
          name: Push Image
          command: docker-compose push

  promote:
    executor: builder
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - checkout
      - run:
          name: Promote Backend
          command: ./.circleci/bin/promote <<pipeline.git.tag>>

workflows:
  version: 2
  build_and_release:
    jobs:
      - build-and-push
          # filters:
          #   branches:
          #     only: master
      - promote:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}/
