version: 2.1

executors:
  builder:
    docker:
      - image: docker:stable

jobs:
  build:
    executor: builder
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Build Image
          command: ./.circleci/bin/build
          environment:
            KONG_DATABASE: off
            KONG_DECLARATIVE_CONFIG: /usr/local/share/kong.yml
            KONG_ADMIN_LISTEN: 0.0.0.0:8001
            KONG_PROXY_LISTEN: 0.0.0.0:8000
            KONG_PLUGINS: bellatrix_bridge,cors,request-size-limiting,prometheus
            KONG_GO_PLUGINS_DIR: /usr/local/share/go-plugins
            KONG_PROXY_ACCESS_LOG: /dev/stdout
            KONG_PROXY_ERROR_LOG: /dev/stderr
            KONG_ADMIN_ACCESS_LOG: /dev/stdout
            KONG_ADMIN_ERROR_LOG: /dev/stderr
            KONG_LOG_LEVEL: info
            SSL_CERTIFICATE_1: MIIFMDCCBBigAwIBAgISA50Hujv3fhrDeKOkg7jX8/moMA0GCSqGSIb3DQEBCwUAMDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQDEwJSMzAeFw0yMDEyMDQxODMyMDVaFw0yMTAzMDQxODMyMDVaMCAxHjAcBgNVBAMTFWFwaS5zdGFnaW5nLnN0b3JkLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJbsn+YROpLtXHRwjJY8FkG63+a/8cZgZATxu66nJ7m//b520bflcoSKVhbKemQRFh7j0+l5UEIqkLaL+BknZ5xzve3RCf3L6QLobCKbdxkZ4l1tMhsMHTp1xzbOL8BTa5UyG4jJewN5koEsq64sd/2LO37lQ1s2lipbPw06LXelEpFIgVa/bnr0Xg+DByP/Htwv2Fy6NxLrqxcv0b5Nknc3HzvuV+UT7Dsg7m5SN3jUKZcfkduMkuTwS9/WEurMvC5X19pWwYBSxtypZ/E6jHgKJE7lbn3+/xnqLjMsW8FwfatqU/oZHzrte3ZHMu9nQ7I9Lui96/+OfxbRSjAWUQMCAwEAAaOCAlAwggJMMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQU1mFG27+4Nfwie3OOAqIWcQZOzAowHwYDVR0jBBgwFoAUFC6zF7dYVsuuUAlA5h+vnYsUwsYwVQYIKwYBBQUHAQEESTBHMCEGCCsGAQUFBzABhhVodHRwOi8vcjMuby5sZW5jci5vcmcwIgYIKwYBBQUHMAKGFmh0dHA6Ly9yMy5pLmxlbmNyLm9yZy8wIAYDVR0RBBkwF4IVYXBpLnN0YWdpbmcuc3RvcmQuY29tMEwGA1UdIARFMEMwCAYGZ4EMAQIBMDcGCysGAQQBgt8TAQEBMCgwJgYIKwYBBQUHAgEWGmh0dHA6Ly9jcHMubGV0c2VuY3J5cHQub3JnMIIBBAYKKwYBBAHWeQIEAgSB9QSB8gDwAHcAXNxDkv7mq0VEsV6a1FbmEDf71fpH3KFzlLJe5vbHDsoAAAF2Lz11owAABAMASDBGAiEA+NubMz0vMVyCL5UuxGTU7T/BU5tAKDNZQqOsBnZdDSICIQDUrcpRHz+xbG09HOlMkMFoFeuYrWbEOhY99d9fTYcbYwB1APZclC/RdzAiFFQYCDCUVo7jTRMZM7/fDC8gC8xO8WTjAAABdi89daUAAAQDAEYwRAIgAxoCRpmUX+kTo66BM2zkvbdGkZ/PuwJrJ/LtSQA9rjwCIB+Bhc1NxFOKspPU8oObyavLMsjNMd95yM58x+OhA0WJMA0GCSqGSIb3DQEBCwUAA4IBAQAeXkYUg+8qGxXCY+XuxlNOfsv8bEqnGsB96HUGtxHQCVwHHhuY23014q8gn5Ub25zYax/Sd53muFGbwQofHGKSBZijEvhBMipgeLse3IeLVAF6qZN2pI+vMmsLGAl53NPlFn6dwYt04jc7D+HVQJBb//bA/09LiFtmAbGVipiSIFeriH0rpC1MIgsmxU5NqeLCynzav1w57PQCkvtNpshU5GKXGXDO72pqXURTn727NoCXqGRjA0YX/zwLK2RFKn+Z6Ce7IBfib7ZGgq1ECQ/sdD43TSeA9XuWPOeu++DmBjH2lzuQfU8ICU6xHfGJhGSWXS/dttsB/yC2y5ViuNn7
            SSL_CERTIFICATE_2: MIIEZTCCA02gAwIBAgIQQAF1BIMUpMghjISpDBbN3zANBgkqhkiG9w0BAQsFADA/MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMTDkRTVCBSb290IENBIFgzMB4XDTIwMTAwNzE5MjE0MFoXDTIxMDkyOTE5MjE0MFowMjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUxldCdzIEVuY3J5cHQxCzAJBgNVBAMTAlIzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuwIVKMz2oJTTDxLsjVWSw/iC8ZmmekKIp10mqrUrucVMsa+Oa/l1yKPXD0eUFFU1V4yeqKI5GfWCPEKpTm71O8Mu243AsFzzWTjn7c9p8FoLG77AlCQlh/o3cbMT5xys4Zvv2+Q7RVJFlqnBU840yFLuta7tj95gcOKlVKu2bQ6XpUA0ayvTvGbrZjR8+muLj1cpmfgwF126cm/7gcWt0oZYPRfH5wm78Sv3htzB2nFd1EbjzK0lwYi8YGd1ZrPxGPeiXOZT/zqItkel/xMY6pgJdz+dU/nPAeX1pnAXFK9jpP+Zs5Od3FOnBv5IhR2haa4ldbsTzFID9e1RoYvbFQIDAQABo4IBaDCCAWQwEgYDVR0TAQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAYYwSwYIKwYBBQUHAQEEPzA9MDsGCCsGAQUFBzAChi9odHRwOi8vYXBwcy5pZGVudHJ1c3QuY29tL3Jvb3RzL2RzdHJvb3RjYXgzLnA3YzAfBgNVHSMEGDAWgBTEp7Gkeyxx+tvhS5B1/8QVYIWJEDBUBgNVHSAETTBLMAgGBmeBDAECATA/BgsrBgEEAYLfEwEBATAwMC4GCCsGAQUFBwIBFiJodHRwOi8vY3BzLnJvb3QteDEubGV0c2VuY3J5cHQub3JnMDwGA1UdHwQ1MDMwMaAvoC2GK2h0dHA6Ly9jcmwuaWRlbnRydXN0LmNvbS9EU1RST09UQ0FYM0NSTC5jcmwwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjANBgkqhkiG9w0BAQsFAAOCAQEA2UzgyfWEiDcx27sT4rP8i2tiEmxYt0l+PAK3qB8oYevO4C5z70kHejWEHx2taPDY/laBL21/WKZuNTYQHHPD5b1tXgHXbnL7KqC401dk5VvCadTQsvd8S8MXjohyc9z9/G2948kLjmE6Flh9dDYrVYA9x2O+hEPGOaEOa1eePynBgPayvUfLqjBstzLhWVQLGAkXXmNs+5ZnPBxzDJOLxhF2JIbeQAcH5H0tZrUlo5ZYyOqA7s9pO5b85o3AM/OJ+CktFBQtfvBhcJVd9wvlwPsk+uyOy2HI7mNxKKgsBTt375teA2TwUdHkhVNcsAKX1H7GNNLOEADksd86wuoXvg==
            SSL_CERTIFICATE_PRIVATE_KEY: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCW7J/mETqS7Vx0cIyWPBZBut/mv/HGYGQE8buupye5v/2+dtG35XKEilYWynpkERYe49PpeVBCKpC2i/gZJ2ecc73t0Qn9y+kC6Gwim3cZGeJdbTIbDB06dcc2zi/AU2uVMhuIyXsDeZKBLKuuLHf9izt+5UNbNpYqWz8NOi13pRKRSIFWv2569F4Pgwcj/x7cL9hcujcS66sXL9G+TZJ3Nx877lflE+w7IO5uUjd41CmXH5HbjJLk8Evf1hLqzLwuV9faVsGAUsbcqWfxOox4CiRO5W59/v8Z6i4zLFvBcH2ralP6GR867Xt2RzLvZ0OyPS7ovev/jn8W0UowFlEDAgMBAAECggEADgwwReXMoehd9qiTLViiabPPK1cqVeCa7qrhYTxFwlBQee3tT0SYCCYoJS7rfWzpti5WhyC3i7ESjyswCIdWaYWMZBpU576XDaI8jmwSBdAW9cM4KrRR9CMKS9udLjWViemEDpNSU9x4+nUB9dBFyt+uxfzo7BCEoaSklcKYgM5D9yBr+VpVf2kiT917mIW2Mv91qoWGNNxJLwmZaeAuyAZMllA+2h/8//xueD+Gt11ly07WnGi6lR4nJUioKljmqYCqNfyi6WDtIIQcM7M27Cu9VkWDYPp8jCKVPIfCupBH+bO0P/2q4dVArqbJVCCW/UX+oWeZc3kZXe8O8sVuwQKBgQDIQvPmqPyYSEDYEs1D0vQEoeZA4+ZKXAKgFpBtyjWJTwnZYIIvrvTkk2I1FVl81wG93zqwef0DqUax1MdH/LY1nJ8Qt5dcrJ4vjoxSks2m42iv4GY52AXWI8gW3GQIg6pWzXJlRc6ZTQFbGxnWSqGbqYQcCjlDqMJx5Sv+s3cD2QKBgQDA7ksSzGJcQIYgYnJ4XOg9SFGfHF225XkoEnfBJIp+qAwtUpMNwas8s/B6XkJ3h/ciqnAhieCDvY/oIDexHrmm3fZl1BDFxUaIIutdOYTKv1NVH6WUD6cCEuAPp3xPyVCJfaAOG8kkwRiBjmZFMAXRwVZe8GL2xdG5TNKVGr0eOwKBgGrW7XCdr0U/Jvkf7srEfNML3N+5tl7tf6kQ4LTyMGW0+TgzuMDfwl9AEiDn5vonaxJ1ScZlDospgEHXlwnc1Qj9Kg+tIt+aaDpO/qX/FCB5KpzKRz+M9HAuXs1zfxrbw8DTkrhc6b/3yUVly/77igSWB5k+CxcBrds9vJ8B9/jhAoGAB8TQsxYV098pR36PW3dqRqV12/FZeLbu1QVBWz6scQM1UlHj6AbnbU9VnKfVB1krQ3MXhtI1fziP5en+NBynnyeK93i9oCkcePjm/18EkOF5apEWqsqij/vQl/DHmbLiklbDri3CQL+hy/2+8oRHh7XAU5xcb9Fxa4PDawujl+cCgYB4lorJxIRWvz4hj5OGvDPMqgidAGstWNOMB8VMWL08fWwU0qODc1lqMLoYyc1RLwO53p6b2/k/bdsn36ANyOxYCnbyb6f2sL/SA57Il0re5gh9Mj1qOC4jSmeDxmloSHcZpho9QNLGL3cQ0BK0XM3/ldS8ZLTW4wGQjcpeiYW1XQ==
            SNI_NAME: api.staging.stord.com
      - run:
          name: Create Workspace
          command: mkdir -p workspace
      - run:
          name: Store Tagged Artifact In CircleCI Workspace
          command: docker save -o workspace/kong-tagged-artifact gcr.io/stord-nonprod/kong:${CIRCLE_WORKFLOW_ID}
      - persist_to_workspace:
          root: workspace
          paths:
            - kong-tagged-artifact

  push-to-gcr:
    executor: builder
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: Authenticate with GCR
          command: echo $NONPROD_GCLOUD_SERVICE_KEY | docker login -u _json_key --password-stdin https://gcr.io
      - run:
          name: Load Tagged Artifact from CircleCI Workspace
          command: docker load -i /tmp/workspace/kong-tagged-artifact
      - run:
          name: Push to GCR
          command: ./.circleci/bin/push-to-gcr

  promote:
    executor: builder
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - checkout
      - run:
          name: Promote Backend
          command: ./.circleci/bin/promote <<pipeline.git.tag>>

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - push-to-gcr:
          requires:
            - build
          # filters:
          #   branches:
          #     only: master
      - promote:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}/
