image:
  repository: gcr.io/stord-nonprod/kong
  tag: ${DOCKER_IMAGE_TAG}
  pullSecrets:
    - gcr-access-key

serviceMonitor:
  enabled: true

ingressController:
  enabled: false
  installCRDs: false

migrations:
  preUpgrade: false
  postUpgrade: false
runMigrations: false

postgresql:
  enabled: false

env:
  database: "off"
  plugins: user_management_bridge,cors,request-size-limiting,correlation-id,traceheaders,zipkin
  pluginserver_names: user_management_bridge
  pluginserver_user_management_bridge_start_cmd: /usr/local/bin/user_management_bridge
  pluginserver_user_management_bridge_query_cmd: /usr/local/bin/user_management_bridge -dump
  declarative_config: /usr/local/share/kong.yml
  nginx_proxy_client_body_buffer_size: "32M"
  nginx_proxy_large_client_header_buffers: "16 16k"
  nginx_proxy_client_header_buffer_size: "16k"
  nginx_http_client_max_body_size: 0
  nginx_http_proxy_buffer_size: "32M"
  nginx_http_proxy_buffers: "16 32M"
  datadog_agent_host:
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP

admin:
  enabled: false
  useTLS: false
  tls:
    enabled: false
  http:
    enabled: true

resources:
  limits:
    cpu: 1.5
    memory: 2G
  requests:
    cpu: 1
    memory: 2G

proxy:
  enabled: true
  useTLS: false
  tls:
    enabled: false
  http:
    enabled: true
  type: ClusterIP

podLabels:
  tags.datadoghq.com/env: dev
  tags.datadoghq.com/service: kong
  tags.datadoghq.com/version: <VERSION>

autoscaling:
  enabled: false
