tolerations:
  - key: node.kubernetes.io/not-ready
    operator: Exists
    effect: NoExecute
    tolerationSeconds: 300
  - key: node.kubernetes.io/unreachable
    operator: Exists
    effect: NoExecute
    tolerationSeconds: 300

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - kong
          topologyKey: topology.kubernetes.io/zone
        weight: 100

podAnnotations:
  sidecar.istio.io/proxyMemory: "1Gi"
  sidecar.istio.io/proxyMemoryLimit: "1Gi"
  sidecar.istio.io/proxyCPU: "100m"
  sidecar.istio.io/proxyCPULimit: "1"

image:
  repository: gcr.io/stord-production/kong
  tag: ${DOCKER_IMAGE_TAG}
  pullSecrets:
    - gcr-access-key

serviceMonitor:
  enabled: true

ingressController:
  enabled: false
  installCRDs: false

migrations:
  preUpgrade: false
  postUpgrade: false
runMigrations: false

postgresql:
  enabled: false

env:
  database: "off"
  plugins: user_management_bridge,cors,request-size-limiting,correlation-id,traceheaders,zipkin
  pluginserver_names: user_management_bridge
  pluginserver_user_management_bridge_start_cmd: /usr/local/bin/user_management_bridge
  pluginserver_user_management_bridge_query_cmd: /usr/local/bin/user_management_bridge -dump
  declarative_config: /usr/local/share/kong.yml
  datadog_agent_host:
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP

admin:
  enabled: true
  useTLS: false
  tls:
    enabled: false
  http:
    enabled: true

resources:
  limits:
    cpu: 1.5
    memory: 4G
  requests:
    cpu: 1
    memory: 4G

proxy:
  enabled: true
  useTLS: false
  tls:
    enabled: false
  http:
    enabled: true
  type: ClusterIP

podLabels:
  tags.datadoghq.com/env: production
  tags.datadoghq.com/service: kong
  tags.datadoghq.com/version: <VERSION>

autoscaling:
  enabled: true
  minRepicas: 3
  maxReplicas: 3
