name: CI

on:
  merge_group:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

permissions:
  contents: read

jobs:
  Docker:
    if: ${{ !startsWith(github.head_ref, 'release-please--branches') }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build
        uses: stordco/actions-elixir/docker-build@e125c9eecde83437728201927fd1d7516cb6cee7 # v1.5.4
